# This is a basic workflow to help you get started with Actions

name: Trigger Jenkins Build on PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/CypressTrigger@master
        with:
          url: "https://5206-125-17-251-66.in.ngrok.io"
          user: "yashit"
          token: ${{ 11aa926889dc5225f5eeaaa58b00449db7 }}
          job: "CypressStorefront"
